#!/usr/bin/perl -w

#use the CGI.pm module
#use CGI qw/:standard/;

#------------------------------------------------------------
#
#          This is Denny's code for unwrapping the form replies
#
my($zzi,@marked,$qn,$an);
binmode STDIN;
read STDIN,$zzi,$ENV{CONTENT_LENGTH};
$zzi =~ s/\s$//g;
@marked = split(/&/,$zzi);
foreach $input (@marked) {
    ($qn,$an) = split(/=/,$input);
    $an =~ tr/+/ /;
    $an =~ s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/eg;
    $an =~ s/~!/ ~!/g;
    $in{$qn} = $an;
    }


#$server = $ENV{'SERVER_NAME'};
#$dirMain = $ENV{'DOCUMENT_ROOT'};
#$dirMAD  = $ENV{'MADGRAPH_BASE'};

#------------------------------------------------------------
# read in the values passed from the form
#------------------------------------------------------------

# dir
$dir  = $in{dir_name};
#$url  = $in{url_name};

$uname=$ENV{'REMOTE_USER'};
if ($uname ne ''){
system("cd /nfs/madgraph/AMCATNLO/$uname/; rm -rf *");
}
##system ("rm -rf $dir");
#
#   Flush outputs immediately
#
#exec("/usr/bin/perl","$dirMAD/WWW/cgi-bin/web_dbhtml-pl") if -e "$dirMAD/WWW/cgi-bin/web_dbhtml-pl";
$| = 1;
print "Content-type: text/html\n\n";
print  "<HTML> <HEAD> \n";
print "<META HTTP-EQUIV=\"Refresh\" CONTENT=\"1\; ";
print "URL=$ENV{'HTTP_REFERER'}\"> \n";
print "</BODY></HTML> \n \n";
#
#   That's all folks!
#
close(STDOUT);
close(STDERR);
close(STDIN);


