#!/usr/bin/perl -w

#use the CGI.pm module
use CGI;

#------------------------------------------------------------
# set variables for the most common path names
#------------------------------------------------------------

$dirDATA = $ENV{'MADGRAPH_DATA'};
#$dirHTML = "MadGraphData";
$server = $ENV{'SERVER_NAME'};

#------------------------------------------
# Find a free directory in the private area
#------------------------------------------

# first check private dir exists and if not create it

  $uname = $ENV{REMOTE_USER};
  if(! -e "$dirDATA/$uname" ){ 
  system("mkdir $dirDATA/$uname")};
  $directory="$dirDATA/$uname";
  
#------------------------------------------------------------
# Upload the form from the web
#------------------------------------------------------------
  $query = new CGI; 

  $filename = $query->param("proc_card"); 
  $filename =~ s/.*[\/\\](.*)/$1/; 
  
  $upload_filehandle = $query->upload("proc_card");

  if(-e "$directory/proc_card.dat"){system("rm -f $directory/proc_card.dat")};    
  open(FILE,">$directory/proc_card.dat") or WriteError("File $directory/proc_card.dat could not be opened");
  
  $ok=0;
  
  @content=<$upload_filehandle>;
  
  foreach $line (@content) {
  
     if($line =~ /Begin(.+)MODEL/){$ok++}
     if($line =~ /End(.+)MODEL/){$ok++}
     if($line =~ /Begin(.+)PROCESS/){$ok++}
     if($line =~ /End(.+)PROCESS/){$ok++}   
     
  }
  
  if($ok<4) {
      WriteError("File $filename empty or absent or not correct. Please provide another file");
  }
  
  foreach $line (@content) {
  
     if(length($line)>1){print FILE $line};
     
  }
    
  close(FILE);

system("tr -d '\r' < $directory/proc_card.dat > $directory/tmp.txt; mv -f $directory/tmp.txt $directory/proc_card.dat");

#------------------------------------------------------------
# Open the resulting card
#------------------------------------------------------------

open(CARD,"<$directory/proc_card.dat") or
  WriteError("The resulting proc_card could not be opened.");


#
#   Flush outputs immediately
#
$| = 1;
print "Content-type: text/html\n\n";
print "<HTML> <HEAD> \n";
print "</HEAD>\n";
print "<FORM METHOD=\"POST\" ACTION=\"http://$server/cgi-bin/NewProcess/webnewprocess-pl\" >\n";
print "<INPUT TYPE=HIDDEN NAME=callfrom  VALUE=\"upload\">\n";
print "<CENTER> File upload ok <BR>";
print "<INPUT TYPE=SUBMIT VALUE=\"Continue\"> \n";
print "</center>";
print "<BR><hr>\n";
print "Resulting proc_card.dat:\n";
print "<PRE>\n";
while(<CARD>){
  print "$_";
}
print "</PRE>\n";
close CARD;
print "</BODY></HTML> \n \n";
#
#   That's all folks!
#

#------------------------------------------------------------
# Display error message in browser and kill process
#------------------------------------------------------------

sub WriteError {
$errormsg=shift;
$| = 1;
print "Content-type: text/html\n\n";
print "<HTML>\n<HEAD> \n";
print "<TITLE>Proc card upload failed</TITLE></HEAD>\n<BODY>\n";
print "<H2>Proc upload failed</H2>\n";
print "$errormsg";
print "<BR>Click the \"backwards\" button in you browser and correct the error.\n";
print "</BODY>\n</HTML>\n";
die;
}




